name: var
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.9.24=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py310h06a4308_0
  - python=3.10.14=h955ad1f_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - tzdata=2024a=h04d1e81_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - accelerate==0.34.2
      - astunparse==1.6.3
      - braceexpand==0.1.7
      - certifi==2024.8.30
      - charset-normalizer==3.3.2
      - click==8.1.7
      - docker-pycreds==0.4.0
      - docstring-parser==0.16
      - einops==0.8.0
      - filelock==3.16.1
      - flatbuffers==24.3.25
      - fsspec==2024.9.0
      - gast==0.6.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - google-pasta==0.2.0
      - grpcio==1.66.2
      - h5py==3.12.1
      - huggingface-hub==0.25.1
      - idna==3.10
      - jinja2==3.1.4
      - keras==3.5.0
      - libclang==18.1.1
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - mdurl==0.1.2
      - ml-dtypes==0.4.1
      - mpmath==1.3.0
      - mypy-extensions==1.0.0
      - namex==0.0.8
      - networkx==3.3
      - numpy==1.23.5
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==9.1.0.70
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.20.5
      - nvidia-nvjitlink-cu12==12.6.77
      - nvidia-nvtx-cu12==12.1.105
      - opt-einsum==3.4.0
      - optree==0.12.1
      - packaging==24.1
      - peft==0.13.0
      - pillow==10.4.0
      - platformdirs==4.3.6
      - protobuf==4.25.5
      - psutil==6.0.0
      - pygments==2.18.0
      - pytz==2024.2
      - pyyaml==6.0.2
      - regex==2024.9.11
      - requests==2.32.3
      - rich==13.9.1
      - ruamel-yaml==0.18.6
      - ruamel-yaml-clib==0.2.8
      - safetensors==0.4.5
      - scipy==1.14.1
      - sentry-sdk==2.15.0
      - setproctitle==1.3.3
      - six==1.16.0
      - smmap==5.0.1
      - sympy==1.13.3
      - tensorboard==2.17.1
      - tensorboard-data-server==0.7.2
      - tensorflow==2.17.0
      - tensorflow-io-gcs-filesystem==0.37.1
      - termcolor==2.4.0
      - timm==1.0.9
      - tokenizers==0.20.0
      - torch==2.4.1
      - torchvision==0.19.1
      - tqdm==4.66.5
      - transformers==4.45.1
      - triton==3.0.0
      - typed-argument-parser==1.10.1
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - urllib3==2.2.3
      - wandb==0.18.3
      - webdataset==0.2.100
      - werkzeug==3.0.4
      - wrapt==1.16.0
prefix: /opt/conda/envs/var
